import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DEFAULT_CONTENT } from "../lib/content-schema";
import { fingerprint, walkLeaves } from "../lib/content-diff";

/**
 * Every value the site document has ever shipped as a default, and no
 * longer does, fingerprinted into `lib/retired-defaults.json`.
 *
 * A dashboard save made before 18 September 2026 stored the whole document,
 * defaults included. Those leftovers are told apart from the couple's own
 * edits by this list: a stored value that matches an old default is dropped
 * on read (`dropRetired` in lib/content-diff.ts) so the current one shows.
 *
 * Reads the two files that make the defaults (lib/constants.ts and
 * lib/content-schema.ts) at every commit that touched them, evaluates
 * DEFAULT_CONTENT there, and keeps the fingerprints that differ from the
 * working tree's. Run it after any change to those files, before committing:
 *
 *   npm run retired
 *
 * It needs git history, so it is part of `npm run verify` (local), not of
 * `npm run check` (which also runs on Vercel, where the clone is shallow).
 */

const ROOT = process.cwd();
const OUT = join(ROOT, "lib", "retired-defaults.json");
const FILES = ["lib/constants.ts", "lib/content-schema.ts"];
const TSX = join(ROOT, "node_modules", "tsx", "dist", "cli.mjs");

const git = (...args: string[]) =>
  execFileSync("git", args, { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024, stdio: ["ignore", "pipe", "ignore"] });

const commits = git("log", "--format=%H", "--", ...FILES).split(/\r?\n/).filter(Boolean);

const current = new Set<string>();
walkLeaves(DEFAULT_CONTENT, (path, leaf) => current.add(fingerprint(path, leaf)));

const retired = new Set<string>();
const work = join(tmpdir(), `retired-defaults-${process.pid}`);
let evaluated = 0;

for (const sha of commits) {
  let schema: string;
  let constants: string;
  try {
    schema = git("show", `${sha}:lib/content-schema.ts`);
    constants = git("show", `${sha}:lib/constants.ts`);
  } catch {
    continue; // the document did not exist yet at this commit
  }
  const dir = join(work, sha.slice(0, 12));
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "constants.ts"), constants);
  writeFileSync(join(dir, "content-schema.ts"), schema.replace(/from "@\/lib\/constants"/g, 'from "./constants"'));
  writeFileSync(
    join(dir, "dump.ts"),
    'import { DEFAULT_CONTENT } from "./content-schema";\nprocess.stdout.write(JSON.stringify(DEFAULT_CONTENT));\n',
  );
  let json: string;
  try {
    json = execFileSync(process.execPath, [TSX, join(dir, "dump.ts")], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024, stdio: ["ignore", "pipe", "ignore"] });
  } catch {
    console.warn(`[retired] could not evaluate defaults at ${sha.slice(0, 7)}, skipped`);
    continue;
  }
  evaluated += 1;
  walkLeaves(JSON.parse(json), (path, leaf) => {
    const fp = fingerprint(path, leaf);
    if (!current.has(fp)) retired.add(fp);
  });
}

rmSync(work, { recursive: true, force: true });

const previous = (() => {
  try {
    return JSON.parse(readFileSync(OUT, "utf8")) as { fingerprints?: string[] };
  } catch {
    return null;
  }
})();

const fingerprints = [...retired].sort();
const output = {
  note: "Generated by npm run retired. Fingerprints of default values from earlier commits that the code no longer ships; a stored value matching one is a leftover snapshot, not an edit.",
  newest: commits[0] ?? "",
  commits: evaluated,
  digest: fingerprint("DEFAULT_CONTENT", DEFAULT_CONTENT),
  fingerprints,
};
writeFileSync(OUT, `${JSON.stringify(output, null, 2)}\n`);

const before = previous?.fingerprints?.length ?? 0;
console.log(`[retired] ${evaluated} commits evaluated, ${fingerprints.length} retired defaults (was ${before}).`);
